# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04

sphinx:
  configuration: docs/source/conf.py

python:
  version: "3.9"
  install:
    - method: pip
      requirements: docs/requirements.txt

