name: hicmae
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip=21.1.3
  - python=3.8.10
  - pybedtools==0.7.10
  - bedtools==2.27.1
  - pybigwig>=0.3.10
  - pysam==0.15.3
  - pip:
      - numpy
      - cooler
      - scipy
      


