name: hic_helper
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - pip
  - python
  - pybedtools
  - bedtools
  - pybigwig>=0.3.10
  - pysam
  - cooltools
  - samtools
  - pbgzip
  - gzip
  - pairtools
  - cooler
  - pip:
      - numpy
      - cooler
      - scipy
      - hic2cool
      
      


